LogisticManagement/Models/Consignment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        public int CId { get; set; }
        public string Consignment_Type { get; set; }
        public string Reciver_Name { get; set; }
        public string Reciver_Address { get; set; }
        public string Reciver_MobileNO { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PickupType { get; set; }
    
        public virtual User User { get; set; }
    }
}

LogisticManagement/Models/Tracking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int Bid { get; set; }
        public Nullable<System.DateTime> Consignment_Procurement { get; set; }
        public Nullable<System.DateTime> Consignment_Ready { get; set; }
        public Nullable<System.DateTime> In_Transit { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
    }
}

LogisticManagement/Controllers/ConsignmentController.cs
using LogisticManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using Rotativa;


namespace LogisticManagement.Controllers
{
    public class ConsignmentController : Controller
    {
        private LogisticManagementEntities db = new LogisticManagementEntities();
        [HttpGet]
        // GET: Consignment
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Consignment_booking()
        {
            //ViewBag.name = "Ashish";
            return View();
        }

        public ActionResult UserContactDetails()
        {
            var emailid = TempData["email"];
           User em = db.Users.FirstOrDefault(x => x.Email_ID == emailid);
            if(em == null)
            {
                ViewBag.name = TempData["name"];
                ViewBag.email = TempData["email"];
            }
            else
            {
                ViewBag.name = em.Name;
                ViewBag.email = em.Email_ID;
                ViewBag.mobile = em.MobileNO;
                ViewBag.address = em.Address;

            }
            return View();
        }

        public ActionResult Consignment_Details()
        {
            var id = TempData["id"];
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        public ActionResult Consignment_Details(Consignment cn)
        {
            var pickup = cn.PickupType;
            TempData["Pkic"] = pickup;
            var destination = cn.Reciver_Address;
            TempData["destination"] = destination;
            db.Consignments.Add(cn);
            db.SaveChanges();

            var cid = cn.CId;
            TempData["cid"] = cid;
            TempData["bid"] = cid;

            var time = DateTime.Now;

            Tracking tr = new Tracking() { Bid = cid, Consignment_Procurement = time };
            db.Trackings.Add(tr);
            db.SaveChanges();
            return RedirectToAction("ConfirmationPage");
        }

        [HttpPost]
        public ActionResult Consignment_booking(User us)
        {
            var name = us.Name;
           TempData["name"] = name;
            var email = us.Email_ID;
           TempData["email"] = email;

            User em = db.Users.FirstOrDefault(x => x.Email_ID == us.Email_ID);
            if (em == null)
            {
                return RedirectToAction("UserContactDetails");
            }
            else
            {
                return RedirectToAction("UserContactDetails");
            }
            
        }

        [HttpPost]
        public ActionResult UserContactDetails(User us)
        {
            var source = us.Address;
            TempData["source"] = source;
            User em = db.Users.FirstOrDefault(x => x.Email_ID == us.Email_ID);
            if (em == null)
            {
                db.Users.Add(us);
                db.SaveChanges();
                var id = us.UId;
                TempData["id"] = id;
            }
            else
            {
                var id = em.UId;
                TempData["id"] = id;
            }

            return RedirectToAction("Consignment_Details",us);
        }
        public ActionResult ConfirmationPage()
        {
            
            string pickup = (string)TempData["Pkic"];
            if(pickup == "slf drop")
            {
                var source = TempData["source"];
                ViewBag.source = source;
                var destination = TempData["destination"];
                ViewBag.destination = destination;
                var cid = (int)TempData["cid"];
                TempData["c"] = cid;
                ViewBag.cid = cid;
                Consignment em = db.Consignments.Find(cid);
                return View(em);
            }
            else
            {
                return RedirectToAction("ConformationPage2");
            }
           
        }
        public ActionResult ConformationPage2()
        {
            var source = TempData["source"];
            ViewBag.source = source;
            var destination = TempData["destination"];
            ViewBag.destination = destination;
            int cid = (int)TempData["cid"];
            ViewBag.cid = cid;
            var slot = DateTime.Now.AddDays(1);
            ViewBag.slot = slot;
            TempData["c"] = cid;
           
            Consignment em = db.Consignments.Find(cid);

            return View(em);
        }

        public ActionResult selfDownload()
        {
            
            int c = (int)TempData["c"];
            Consignment consignment = db.Consignments.Find(c);
            var pdfResulst = new ViewAsPdf("ConfirmationPage", consignment);
            
            return pdfResulst;
        }
        public ActionResult reciverDownload()
        {

            int c = (int)TempData["c"];
            Consignment consignment = db.Consignments.Find(c);
            var pdfResulst = new ViewAsPdf("ConfirmationPage", consignment);

            return pdfResulst;
        }

        public ActionResult Tracking()
        {

            return View();
        }

        [HttpPost]
        
        public ActionResult Tracking_Details(int bid)
        {
        int id = bid;
        Tracking t = db.Trackings.Find(id);
        return View(t);
        }


    }
}

LogisticManagement/Views/Consignment/ConfPage.cshtml
@model LogisticManagement.Models.Consignment
@{
    ViewBag.Title = "ConfirmationPage";
}

<h2>Confirmation Slip</h2>
@using (Html.BeginForm("selfDownload", "Consignment"))
{
    <div>
        <label for="Uniquekey" class="form-label">Booking Number :- </label>
        <label id="uniquekey" class="form-label">@ViewBag.cid</label>
        <input type="hidden" value="@ViewBag.cid" name="booking" />

    </div>
    <div>
        <label for="consinment" class="form-label">Coansignment address :- </label>
        <label id="consinment" class="form-label">@ViewBag.source</label>
    </div>
    <div>
        <label for="Source" class="form-label">Source address :- </label>
        <label id="Source" class="form-label">@ViewBag.source</label>
    </div>
    <div>
        <label for="Destination" class="form-label">Destination address :- </label>
        <label id="Destination" class="form-label">@ViewBag.destination</label>
    </div>

    <div><input class="btn btn-primary" type="submit" value="Cilck to downlod pdf"></div>
}

LogisticManagement/Views/Consignment/ConfPage2.cshtml
@model LogisticManagement.Models.Consignment

@{
    ViewBag.Title = "ConfirmationPage";
}

<h2>Confirmation Slip</h2>
<div>
    @{
        var c = 10;
    }
    @ViewBag.cid
</div>
<div>
    <label for="Uniquekey" class="form-label">Booking Number :- </label>
    <label id="uniquekey" class="form-label">@Model.CId</label>
</div>
<br />
<div>
    <label for="exampleFormControlInput1" class="form-label">Coansignment address :- </label>
    <label id="exampleFormControlInput1" class="form-label">@ViewBag.source</label>
</div>
<br />
<div>
    <label for="exampleFormControlInput1" class="form-label">Source address :- </label>
    <label id="exampleFormControlInput1" class="form-label">@ViewBag.source</label>
</div>
<br />
<div>
    <label for="exampleFormControlInput1" class="form-label">Destination address :- </label>
    <label id="exampleFormControlInput1" class="form-label">@ViewBag.destination</label>
</div>
<br />
<div>
    <label for="exampleFormControlInput1" class="form-label">Time slot for pickup :- </label>
    <label id="exampleFormControlInput1" class="form-label">@ViewBag.slot</label>
</div>

LogisticManagement/Views/Consignment/ConfirmationPage.cshtml
@model LogisticManagement.Models.Consignment

@{
    ViewBag.Title = "Confirmation Slip";
}

<h2>ConfirmationPage</h2>


<div>
    <h4>Consignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label for="Uniquekey" class="form-label">Booking Number :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CId)
        </dd>

        <dt>
            <label for="consinment" class="form-label">Coansignment address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Address)
        </dd>

        <dt>
            <label for="exampleFormControlInput1" class="form-label">Source address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Address)
        </dd>
        


        <dt>
            <label for="Destination" class="form-label">Destination address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reciver_Address)
        </dd>


    </dl>
</div>


@using (Html.BeginForm("selfDownload", "Consignment"))
{
    
    <div><input class="btn btn-primary" type="submit" value="Cilck to downlod pdf"></div>

}

LogisticManagement/Views/Consignment/ConformationPage2.cshtml
@model LogisticManagement.Models.Consignment

@{
    ViewBag.Title = "ConformationPage";
}

<h2>Conformation Slip</h2>

<div>
    <h4>Consignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label for="Uniquekey" class="form-label">Booking Number :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CId)
        </dd>

        <dt>
            <label for="consinment" class="form-label">Coansignment address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Address)
        </dd>

        <dt>
            <label for="exampleFormControlInput1" class="form-label">Source address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Address)
        </dd>


        <dt>
            <label for="Destination" class="form-label">Destination address :- </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reciver_Address)
        </dd>

        <dt>
            <label for="exampleFormControlInput1" class="form-label">Time slot for pickup :- </label>
        </dt>

        <dd>
            <label id="exampleFormControlInput1" class="form-label">@ViewBag.slot</label>
        </dd>
        
    </dl>
</div>
@using (Html.BeginForm("reciverDownload", "Consignment"))
{

    <div><input class="btn btn-primary" type="submit" value="Cilck to downlod pdf"></div>

}

LogisticManagement/Views/Consignment/Consignment_Details.cshtml
@model LogisticManagement.Models.Consignment
@{
    ViewBag.Title = "Consignment_Details";
}

<div>
    <h2>Consignment Details</h2>

    @using (Html.BeginForm("Consignment_Details", "Consignment"))
    {
<div>
    <input type="hidden" value="@ViewBag.id" class="form-control" name="UserId" >
</div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Consignment Type</label>
            <input type="text" class="form-control" name="Consignment_Type" id="exampleFormControlInput1" placeholder="Consignment Type">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Reciver Name</label>
            <input type="text" class="form-control" name="Reciver_Name" id="exampleFormControlInput1" placeholder="Reciver name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Reciver Address</label>
            <input type="text" class="form-control" name="Reciver_Address" id="exampleFormControlInput1" placeholder="Reciver Address">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Reciver Mobile NO</label>
            <input type="text" class="form-control" name="Reciver_MobileNO" id="exampleFormControlInput1" placeholder="Reciver 10 digit mobile no">
        </div>
        <br />
        <div>
            <label for="pickup" class="form-label">Pickup Type</label>
            <select name="PickupType" id="pickup">
                <option value="slf drop">Self droping with confirmation slip</option>
                <option value="company Pickup">Request company pickup</option>
            </select>
        </div>


        <br />
        <div><input class="btn btn-primary" type="submit" value="Submit"></div>

    }
</div>

LogisticManagement/Views/Consignment/Consignment_booking.cshtml
@model LogisticManagement.Models.User
@{
    ViewBag.Title = "Consignment Booking";
}

<div>
    <h2>Booking Details</h2>
    @using (Html.BeginForm("Consignment_booking", "Consignment"))
    {
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">User Name</label>
            <input type="text" class="form-control" name="Name" id="exampleFormControlInput1" placeholder="Your name" value="@ViewBag.name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" name="Email_ID" id="exampleFormControlInput1" placeholder="Your email">
        </div>
        <br />
        <div><input class="btn btn-primary" type="submit" value="Next"></div>
        
    }
</div>

LogisticManagement/Views/Consignment/Tracking.cshtml
@{
    ViewBag.Title = "Tracking";
}


@using (Html.BeginForm("Tracking_Details", "Consignment"))
{
    <h2>Consignment Tracking</h2>
    <div>
        <label for="Uniquekey" class="form-label">Enter Booking Number :- </label>
        <input type="number" class="form-control" id="Uniquekey" name ="Bid"  placeholder="Your booking id">
    </div>
 
    <br />
    <div>
        <button type="submit" class="btn btn-primary">Next</button>
    </div>
}

LogisticManagement/Views/Consignment/Tracking_Details.cshtml
@model LogisticManagement.Models.Tracking

@{
    ViewBag.Title = "Tracking_Details";
}

<h2>Tracking_Details</h2>

<div>
    <h4>Tracking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consignment_Procurement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consignment_Procurement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consignment_Ready)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consignment_Ready)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.In_Transit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.In_Transit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delivered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delivered)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LogisticManagement/Views/Consignment/UserContactDetails.cshtml
@model LogisticManagement.Models.User
@{
    ViewBag.Title = "UserContactDetails";
}

<div>
    <h2>UserContactDetails</h2>

    @using (Html.BeginForm("UserContactDetails", "Consignment"))
    {
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">User Name</label>
            <input type="text" class="form-control" name="Name" id="exampleFormControlInput1" placeholder="Your name" value="@ViewBag.name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" name="Email_ID" id="exampleFormControlInput1" placeholder="Your email" value="@ViewBag.email">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Mobile No.</label>
            <input type="text" class="form-control" name="MobileNO" id="exampleFormControlInput1" placeholder="Your 10 digit Mobile No." value="@ViewBag.mobile">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Address</label>
            <input type="text" class="form-control" name="Address" id="exampleFormControlInput1" placeholder="Your Address" value="@ViewBag.address">
        </div>
        <br />
        <div><input class="btn btn-primary" type="submit" value="Next"></div>

    }
</div>